// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBadDUhk5NgRunsZH7hbVMiVmUu__gWIjE',
    appId: '1:848390248196:web:a6d9a4f663aa5d20d2a251',
    messagingSenderId: '848390248196',
    projectId: 'notes-app-8adea',
    authDomain: 'notes-app-8adea.firebaseapp.com',
    storageBucket: 'notes-app-8adea.firebasestorage.app',
    measurementId: 'G-CSXDFPC0W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVIWNyHOD6az_Q2eVOx81ipfSJMogsi0',
    appId: '1:848390248196:android:0e68e8b7db3b3177d2a251',
    messagingSenderId: '848390248196',
    projectId: 'notes-app-8adea',
    storageBucket: 'notes-app-8adea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4v2W40asParmzdQv1-OH-r7mkAWFIG_Y',
    appId: '1:848390248196:ios:ec8b77ca97ee935bd2a251',
    messagingSenderId: '848390248196',
    projectId: 'notes-app-8adea',
    storageBucket: 'notes-app-8adea.firebasestorage.app',
    iosBundleId: 'com.example.notes1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4v2W40asParmzdQv1-OH-r7mkAWFIG_Y',
    appId: '1:848390248196:ios:ec8b77ca97ee935bd2a251',
    messagingSenderId: '848390248196',
    projectId: 'notes-app-8adea',
    storageBucket: 'notes-app-8adea.firebasestorage.app',
    iosBundleId: 'com.example.notes1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBadDUhk5NgRunsZH7hbVMiVmUu__gWIjE',
    appId: '1:848390248196:web:6505b8da07ec0329d2a251',
    messagingSenderId: '848390248196',
    projectId: 'notes-app-8adea',
    authDomain: 'notes-app-8adea.firebaseapp.com',
    storageBucket: 'notes-app-8adea.firebasestorage.app',
    measurementId: 'G-2KJHQ7BYNS',
  );
}
